baseURL: https://aafu.pages.dev/
languageCode: en-us
build:
  writeStats: true
params:
  title: Simone Bertolucci
  author: Simone Bertolucci
  description: Curriculum Vitae
  copyright: >-
    powered by [Hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
  favicons:
    use: true
    metas: |2-
      <link rel="icon" type="image/png" href="./favicon-96x96.png" sizes="96x96" />
      <link rel="icon" type="image/svg+xml" href="./favicon.svg" />
      <link rel="shortcut icon" href="./favicon.ico?" />
      <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png" />
      <link rel="manifest" href="./site.webmanifest" />

  profile:
    name: "Simone Bertolucci"
    location: "CS student based in Pisa"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/simone-bertolucci-b10725259/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/slaimon"
        title: GitHub
      - icon: fa fa-envelope
        url: "mailto:simonebertolucci@proton.me"
        title: Email
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: voluntary
    - item: education
    - item: project
    - item: skill
  aboutme:
    title: About Me
    icon: fas fa-user
    description: |
      Sono un laureando in Informatica all'Università di Pisa in cerca di esperienza lavorativa per arricchire le mie competenze.

      Sono nato il 20/01/1997 e risiedo a **Cisanello, Pisa**
  experience:
    title: Esperienze Lavorative
    icon: fas fa-suitcase
    list:
      - position: Alfabetizzazione Informatica
        dates: 2023 - 2024
        company: Biblioteca Agorà
        url: "https://bibliotecaagora.it/"
        details: |1-
          Ho tenuto quattro edizioni di un corso introduttivo all'uso del PC. L'esperienza mi ha aiutato a sviluppare abilità nel:
          - Parlare in pubblico
          - Esporre concetti complessi
          - Organizzazione
  voluntary:
    title: Volontariato
    icon: fas fa-heart
    list:
      - position: Riparazione PC e assistenza IT
        dates: 2020 - 2021
        institution: Hacking Labs APS
        url: https://hackinglabs.it/
        details: |1-
          - Abilità tecniche
          - Orientamento al cliente
      - position: Organizzatore e Portavoce
        dates: 2019 - 2021
        institution: Earth Strike Lucca
        url: https://www.instagram.com/earthstrikelucca/
        details: |1-
          - Team working
          - Organizzazione di eventi a grande affluenza (>2000 persone)
          - Comunicazione efficace anche in situazioni di conflitto
          - Negoziazione win-win nell'ambito delle politiche comunali
  education:
    title: Formazione
    icon: fas fa-graduation-cap
    list:
      - degree: Laurea in Informatica
        college: Università di Pisa
        dates: 2018 - *oggi*
        details: |1-
          - Analisi e progettazione di algoritmi
          - Programmazione in C, C++, OpenGL, Java, Python, Matlab e Caml
          - Programmazione concorrente su sistemi POSIX
          - Progettazione e interrogazione di database relazionali
          - Progettazione di un sistema software con Visual Paradigm
      - degree: Diploma di Liceo Scientifico
        college: Liceo Scientifico A.Vallisneri
        dates: 2010 - 2015
  project:
    title: Progetti
    icon: fa fa-code
    list:
      - title: Questa pagina web
        url: "#"
        description: Ho creato questa pagina web usando il generatore statico **Hugo**.
      - title: CarOusel
        url: "https://github.com/slaimon/carousel"
        description: Una scena 3D esplorabile con illuminazione e ombre dinamiche, scritta in **C++** con **OpenGL**.
      - title: Crystal Pixels Online Editor
        url: "https://github.com/slaimon/cryxtels-editor"
        description: Un'interfaccia web per creare semplici modelli 3D, basata su **THREE.js**.
      - title: WebGL random-art
        url: "https://slaimon.github.io/webgl-random-art-demo/"
        description: Ho operato l'**ingegneria inversa** su di un vecchio sito e l'ho reso 100 volte più veloce con **WebGL**.
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "C / C++"
        skillrating: 75
      - skill: "HTML / CSS / JS"
        skillrating: 50
      - skill: "Italiano"
        skillrating: 100
      - skill: "Inglese"
        skillrating: 100
      - skill: "Tedesco"
        skillrating: 30
