baseURL: https://aafu.pages.dev/
languageCode: en-us
build:
  writeStats: true
params:
  title: Simone Bertolucci
  author: Simone Bertolucci
  description: Curriculum Vitae
  copyright: >-
    powered by [Hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
  favicons:
    use: true
    metas: |2-
      <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
      <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      <link rel="shortcut icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
      <link rel="manifest" href="/site.webmanifest" />

  profile:
    name: "Simone Bertolucci"
    location: "based in Pisa"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "#"
        title: LinkedIn
      - icon: fab fa-github
        url: "#"
        title: GitHub
      - icon: fa fa-envelope
        url: "mailto:simonebertolucci@proton.me"
        title: Email
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: project
    - item: voluntary
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: |
      Sono un laureando in Informatica all'Università di Pisa in cerca di esperienza lavorativa per arricchire le mie competenze.

      Sono nato il 20/01/1997 e risiedo a **Cisanello, Pisa**
  experience:
    title: Esperienze Lavorative
    icon: fas fa-suitcase
    list:
      - position: Alfabetizzazione Informatica
        dates: 2023 - 2024
        company: Biblioteca Agorà
        url: "https://bibliotecaagora.it/"
        details: |1-
          Ho tenuto quattro edizioni di un corso introduttivo all'uso del PC
      - position: Job Title
        dates: 2018 - 2019
        url: "#"
        company: Company Name
  voluntary:
    title: Volontariato
    icon: fas fa-heart
    list:
      - position: 
        dates: 2020 - 2021
        institution: Hacking Labs APS
  education:
    title: Formazione
    icon: fas fa-graduation-cap
    list:
      - degree: Ph.D. in Subject
        college: University of State-City
        dates: 2013 - 2018
        thesis_title: "Effect of humans on other humans: a study of human behavior."
        thesis_url: "#"
      - degree: M.S. in Subject
        college: University of State-City
        dates: 2013 - 2018
        thesis_title: "Effect of humans on other humans: a study of human behavior."
        thesis_url: "#"
      - degree: B.S. in Subject
        college: University of State-City
        dates: 2004 - 2009
  project:
    title: Progetti
    icon: fa fa-code
    list:
      - title: Project 1
        url: "#"
        description: Description of the project
      - title: Project 2
        url: "#"
        description: Description of the project
      - title: Project 3
        url: "#"
        description: Description of the project
      - title: Project 4
        url: "#"
        description: Description of the project
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Skill 1, Skill 2"
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
  hobby:
    title: Hobby
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Hiking
      - hobby: Baking
